main: com.github.g4memas0n.services.Services
name: Services
version: 1.1.3
description: A plugin that provides moderators god mode while holding service items.
author: G4meMas0n
api-version: 1.16

commands:
  services:
    description: The main services command.
    permission: services.manage
    usage: /<command> (reload|version)

permissions:
  services.manage.*:
    description: Allows to access all commands of this plugin.
    default: false
    children:
      services.manage: true
      services.manage.reload: true
      services.manage.version: true

  services.bypass.*:
    description: Allows to bypass service restrictions and settings.
    default: false
    children:
      services.bypass.grace: true
      services.bypass.restriction: true
      services.bypass.warmup: true

  services.environment.*:
    description: Allows to use services in all service environments.
    default: false
    children:
      services.environment.nether: true
      services.environment.normal: true
      services.environment.the_end: true

  services.item.*:
    description: Allows to use all service items.
    default: false
    children:
      services.item.bedrock: true
      services.item.wooden_axe: true

  services.world.*:
    description: Allows to use services in all service worlds.
    default: false
    children:
      services.world.world: true
      services.world.world_nether: true
      services.world.world_the_end: true