main: de.g4memas0n.services.Services
name: Services
version: 1.1.1
description: A plugin that provides moderators god mode while holding service items.
author: G4meMas0n
api-version: "1.13"

commands:
  services:
    description: The main services command.
    permission: services.use
    usage: /<command> (reload|version)

permissions:
  services.environment.*:
    description: Allows to use services in all service environments.
    default: false
    children:
      services.environment.nether: true
      services.environment.normal: true
      services.environment.the_end: true
  services.item.*:
    description: Allows to use all service items.
    default: false
    children:
      services.item.bedrock: true
      services.item.wooden_axe: true
  services.world.*:
    description: Allows to use services in all service worlds.
    default: false
    children:
      services.world.world: true
      services.world.world_nether: true
      services.world.world_the_end: true